version: '3'
services:
  db:
    image: postgres
    restart: always
    container_name: postgres-zabanie
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ...
      POSTGRES_PASSWORD: ...
      POSTGRES_DB: ...
    volumes:
      - zadanieTTT:/var/lib/postgresql/data

  myapp:
    container_name: zadanie
    build: .
    ports:
      - '9000:9000'
      - '5555:5555'
    environment:
      DATABASE_URL: ...
    depends_on:
      - db

volumes:
  zadanieTTT:





